name: .NET Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET CLI
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Build project
      run: dotnet build -c release
    - name: Run tests
      run: dotnet test -c Release
    - name: Prepare artifacts
      if: startsWith(github.ref, 'refs/tags/') == false
      shell: bash
      run: |
        find "BeatSaverSharp/bin/Release/netstandard2.0" -type f ! -name "BeatSaverSharp.*" -delete
        find "BeatSaverSharp/bin/Release/netstandard2.0" -type f -name "*.deps.json" -delete
        find "BeatSaverSharp/bin/Release/netstandard2.1" -type f ! -name "BeatSaverSharp.*" -delete
        find "BeatSaverSharp/bin/Release/netstandard2.1" -type f -name "*.deps.json" -delete
        cp "LICENSE" "BeatSaverSharp/bin/Release/netstandard2.0/LICENSE.BeatSaverSharp.txt"
        cp "LICENSE" "BeatSaverSharp/bin/Release/netstandard2.1/LICENSE.BeatSaverSharp.txt"
    - name: Upload .NET Standard 2.0 DLLs
      if: startsWith(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v2
      with:
        name: BeatSaverSharp-netstandard2.0-${{ github.sha }}
        path: ./BeatSaverSharp/bin/Release/netstandard2.0/
    - name: Upload .NET Standard 2.1 DLLs
      if: startsWith(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v2
      with:
        name: BeatSaverSharp-netstandard2.1-${{ github.sha }}
        path: ./BeatSaverSharp/bin/Release/netstandard2.1/
    - name: Publish to NuGet
      if: startsWith(github.ref, 'refs/tags/') == true
      run: dotnet nuget push --skip-duplicate --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json **\*.nupkg
