name: .NET Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    # Set Path workaround for https://github.com/actions/virtual-environments/issues/263
    - name: "Temp step to Set Path for Windows"
      run: |
        echo "::add-path::C:\Program Files\Git\mingw64\bin"
        echo "::add-path::C:\Program Files\Git\usr\bin"
        echo "::add-path::C:\Program Files\Git\bin"
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build solution
      run: dotnet build -c release BeatSaverSharp/BeatSaverSharp.csproj
    - name: Prepare artifact
      if: contains(github.ref, 'refs/tags/') == false
      shell: bash
      run: |
        find "BeatSaverSharp/bin/Release/netstandard2.0" -type f ! -name "BeatSaverSharp.*" -delete
        find "BeatSaverSharp/bin/Release/netstandard2.0" -type f -name "*.deps.json" -delete
        find "BeatSaverSharp/bin/Release/netstandard2.1" -type f ! -name "BeatSaverSharp.*" -delete
        find "BeatSaverSharp/bin/Release/netstandard2.1" -type f -name "*.deps.json" -delete
        cp "LICENSE" "BeatSaverSharp/bin/Release/netstandard2.0/LICENSE.BeatSaverSharp.txt"
        cp "LICENSE" "BeatSaverSharp/bin/Release/netstandard2.1/LICENSE.BeatSaverSharp.txt"
    - name: Upload .NET Standard 2.0 DLLs
      if: contains(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v1
      with:
        name: BeatSaverSharp-netstandard2.0-${{ github.sha }}
        path: ./BeatSaverSharp/bin/Release/netstandard2.0
    - name: Upload .NET Standard 2.1 DLLs
      if: contains(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v1
      with:
        name: BeatSaverSharp-netstandard2.1-${{ github.sha }}
        path: ./BeatSaverSharp/bin/Release/netstandard2.1
    - name: Publish to NuGet
      if: contains(github.ref, 'refs/tags/') == true
      run: dotnet nuget push --skip-duplicate --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json **\*.nupkg
