name: .NET Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET CLI
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100-rc.2.20479.15'
    - name: Build project
      run: dotnet build -c release
    - name: Run tests
      run: dotnet test ./BeatSaverSharp.Tests -c Release --logger GitHubActions
    - name: Prepare artifacts
      id: prepare
      if: startsWith(github.ref, 'refs/tags/') == false
      shell: bash
      run: |
        echo ::set-output name=version::`git rev-parse --short HEAD`
        find "BeatSaverSharp/bin/Release" -type f -name "*.deps.json" -delete
        cp "LICENSE" "BeatSaverSharp/bin/Release/netstandard2.0/LICENSE.BeatSaverSharp.txt"
        cp "LICENSE" "BeatSaverSharp/bin/Release/netstandard2.1/LICENSE.BeatSaverSharp.txt"
    - name: Upload .NET Standard 2.0 DLLs
      if: startsWith(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v2
      with:
        name: BeatSaverSharp-${{ steps.prepare.outputs.version }}-netstandard2.0
        path: ./BeatSaverSharp/bin/Release/netstandard2.0/
    - name: Upload .NET Standard 2.1 DLLs
      if: startsWith(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v2
      with:
        name: BeatSaverSharp-${{ steps.prepare.outputs.version }}-netstandard2.1
        path: ./BeatSaverSharp/bin/Release/netstandard2.1/
    - name: Publish to NuGet
      if: startsWith(github.ref, 'refs/tags/') == true
      run: dotnet nuget push --skip-duplicate --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json **\*.nupkg
